# EmbedRegexTemplates.cmake — generate `regex_templates_embedded.cpp`
# from every `*.json` under `${INPUT_DIR}`, writing the result to
# `${OUTPUT_FILE}`. Each JSON becomes one
# `loglib::internal::EmbeddedRegexTemplate` entry, with its bytes
# emitted as a C++ string literal (backslashes, quotes, newlines,
# CRs, and tabs escaped).
#
# Invocation (see `library/CMakeLists.txt`):
#   include(cmake/EmbedRegexTemplates.cmake)
#   embed_regex_templates(
#     INPUT_DIR  ${CMAKE_CURRENT_SOURCE_DIR}/data/regex_templates
#     OUTPUT_FILE ${CMAKE_CURRENT_BINARY_DIR}/regex_templates_embedded.cpp
#   )
#
# Idempotent: the inputs are registered as `CMAKE_CONFIGURE_DEPENDS`,
# so editing a JSON re-runs configure and regenerates the file.

function(embed_regex_templates)
    cmake_parse_arguments(EMBED "" "INPUT_DIR;OUTPUT_FILE" "" ${ARGN})
    if(NOT EMBED_INPUT_DIR OR NOT EMBED_OUTPUT_FILE)
        message(FATAL_ERROR "embed_regex_templates() requires INPUT_DIR and OUTPUT_FILE")
    endif()

    # Sort alphabetically for a deterministic TU across machines
    # and across `file(GLOB)` implementations.
    file(GLOB _json_files LIST_DIRECTORIES false "${EMBED_INPUT_DIR}/*.json")
    list(SORT _json_files)

    # Register inputs as configure-time dependencies so a JSON edit
    # re-runs configure and regenerates the file.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_json_files})

    # Build the generated file in memory, then write once.
    set(_header
        [=[// Auto-generated by cmake/EmbedRegexTemplates.cmake.
// Source: library/data/regex_templates/*.json
// Do NOT edit by hand; edit the source JSONs and rebuild.

#include "loglib/internal/embedded_regex_templates.hpp"

#include <array>
#include <string_view>

namespace loglib::internal
{
namespace
{
]=]
    )

    set(_literals "")
    set(_entries "")
    set(_index 0)
    foreach(_json_path IN LISTS _json_files)
        get_filename_component(_basename "${_json_path}" NAME)
        file(READ "${_json_path}" _raw_json)

        # Escape for a C++ string literal. Order matters:
        # backslash first, so it doesn't double-escape our own
        # escapes below.
        string(REPLACE "\\" "\\\\" _escaped "${_raw_json}")
        string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
        # Real newline / CR / tab bytes -> escape sequences.
        string(REPLACE "\n" "\\n\"\n        \"" _escaped "${_escaped}")
        string(REPLACE "\r" "\\r" _escaped "${_escaped}")
        string(REPLACE "\t" "\\t" _escaped "${_escaped}")

        string(APPEND _literals "constexpr std::string_view K_JSON_${_index} =\n" "        \"${_escaped}\";\n\n")
        string(APPEND _entries "    EmbeddedRegexTemplate{ \"${_basename}\", K_JSON_${_index} },\n")
        math(EXPR _index "${_index} + 1")
    endforeach()

    set(_entries_block "constexpr std::array<EmbeddedRegexTemplate, ${_index}> K_ENTRIES = {{\n${_entries}}};\n\n")

    set(_footer
        [=[} // namespace

std::span<const EmbeddedRegexTemplate> EmbeddedBuiltinRegexTemplates() noexcept
{
    return std::span<const EmbeddedRegexTemplate>(K_ENTRIES.data(), K_ENTRIES.size());
}

} // namespace loglib::internal
]=]
    )

    set(_contents "${_header}${_literals}${_entries_block}${_footer}")

    # Only rewrite when the content changes, so no-op reconfigures
    # don't trigger a "modified" timestamp on dependent targets.
    set(_should_write TRUE)
    if(EXISTS "${EMBED_OUTPUT_FILE}")
        file(READ "${EMBED_OUTPUT_FILE}" _existing)
        if(_existing STREQUAL _contents)
            set(_should_write FALSE)
        endif()
    endif()
    if(_should_write)
        file(WRITE "${EMBED_OUTPUT_FILE}" "${_contents}")
        message(STATUS "Embedded ${_index} regex templates into ${EMBED_OUTPUT_FILE}")
    endif()
endfunction()
