name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  QT_VERSION: "6.6.*"
  APP_NAME: "StructuredLogViewer"

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: "linux"
          target: "desktop"
          arch: "gcc_64"

      - name: Install build tools
        run: sudo apt-get install -y cmake libfuse2

      - name: Build
        run: |
          mkdir build
          cd build
          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Install linuxdeploy and plugin
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-plugin-qt-x86_64.AppImage

      - name: Package application
        run: |
          APP_DIR="${{ env.APP_NAME }}.AppDir"
          mkdir -p $APP_DIR/usr/bin
          mkdir -p $APP_DIR/usr/lib
          mkdir -p $APP_DIR/usr/share/applications
          mkdir -p $APP_DIR/usr/share/icons/hicolor/256x256/apps
          cp build/bin/Release/${{ env.APP_NAME }} $APP_DIR/usr/bin/
          cp -r build/bin/Release/tzdata $APP_DIR/usr/share/
          cp resources/icon-white.png $APP_DIR/usr/share/icons/hicolor/256x256/apps/${{ env.APP_NAME }}.png
          cp resources/app.desktop $APP_DIR/usr/share/applications/${{ env.APP_NAME }}.desktop
          ./linuxdeploy-x86_64.AppImage --executable=build/bin/Release/${{ env.APP_NAME }} --appdir=$APP_DIR --plugin qt
          mv ${{ env.APP_NAME }}*.AppImage ${{ env.APP_NAME }}.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.APP_NAME }}-linux
          path: ./*

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.APP_NAME }}.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"

      - name: Install build tools
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y

      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          set CMAKE_BUILD_PARALLEL_LEVEL=%NUMBER_OF_PROCESSORS%
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Package application
        shell: powershell
        run: |
          mv build/bin/Release ${{ env.APP_NAME }}
          cd ${{ env.APP_NAME }}
          windeployqt --release ${{ env.APP_NAME }}.exe
          Compress-Archive -Path . -DestinationPath ../${{ env.APP_NAME }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows
          path: ./*

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.APP_NAME }}.zip
