name: Build Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.6.3"
          host: "linux"
          target: "desktop"
          arch: "gcc_64"

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Install linuxdeployqt
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Package application
        run: |
          cd build
          ../linuxdeployqt-continuous-x86_64.AppImage myapp -appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-linux
          path: build/*.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.6.3"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Package application
        run: |
          cd build
          windeployqt myapp.exe
          powershell Compress-Archive -Path * -DestinationPath myapp-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-windows
          path: build/myapp-windows.zip
