name: Build Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.6.3"
          host: "linux"
          target: "desktop"
          arch: "gcc_64"

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.6.3"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
